#------------#
#   bash     #
#------------#

umask 077   # file protection no read or write for others
            # umask 022 is no write but read for others

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
ulimit -c 0
set -o noclobber
alias cp='cp -i'    # prompt before overwriting file
alias mv='mv -i'    # prompt before overwriting file
alias rm='rm -i'    # prompt before removing file

# enable bash completion in interactive shells
if [ -f /etc/bash_completion ] ; then
   . /etc/bash_completion
fi

# fancy prompt
case "$TERM" in
    xterm*|screen*)
        case "$HOSTNAME" in
            MB*|mb*)
                MY_PROMPT_COLOR="35"  # Magenta
            ;;
            *.clsp.jhu.edu)
                MY_PROMPT_COLOR="36"  # Cyan
            ;;
            a??|b??|c??)
                MY_PROMPT_COLOR="32"  # Green
            ;;
            *)
                MY_PROMPT_COLOR="31"  # Red
            ;;
        esac
        PSSUF="\[\033[01;${MY_PROMPT_COLOR}m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PSSUF"
        ;;
    *)
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
    ;;
esac

# Put any local aliases or settings below this line.

# Colored ls; not portable to linux.
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

# Utility for finding a variable, etc. in the current folder.
# 
# No, seriously. This is probably the best thing I've written in bash,
# and it's crazy helpful.
function lookfor() {
  grep --color -nriI "$@" .
}
export -f lookfor

# added by Anaconda3 4.2.0 installer
export PATH="/Users/Arya/anaconda/bin:$PATH"

alias workon='source activate'
alias donewith='source deactivate'

export PATH=~/.local/bin:$PATH

export PATH=~/amplide.macosx64:$PATH

EDITOR="subl"; export EDITOR
VISUAL="$EDITOR"; export VISUAL  #even better
